-- "wallpaper" colorscheme: driven by nvim/lua/colors_generated.lua, which is
-- regenerated by sketchybar/theme/generate.sh whenever the desktop wallpaper
-- changes. This file is the static logic; only colors_generated.lua changes.
--
-- colors_generated.lua is gitignored (machine-specific) -- init.lua only
-- activates "wallpaper" when that file exists (falls back to the real
-- tokyonight-night otherwise), so it's safe to assume it's here.
--
-- Palette is shaped like tokyonight.nvim's (see :h tokyonight) on purpose —
-- lualine.lua reads the same field names, just from a different module.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "wallpaper"

local c = require("colors_generated")

---@param group string
---@param opts vim.api.keyset.highlight
local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ── Base UI ──────────────────────────────────────────────────────────────────

hi("Normal", { fg = c.fg, bg = c.none })
hi("NormalNC", { fg = c.fg, bg = c.none })
hi("NormalFloat", { fg = c.fg_float, bg = c.bg_float })
hi("FloatBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("FloatTitle", { fg = c.blue1, bg = c.bg_float, bold = true })
hi("Cursor", { fg = c.bg, bg = c.fg })
hi("CursorLine", { bg = c.bg_highlight })
hi("CursorLineNr", { fg = c.blue1, bold = true })
hi("CursorColumn", { bg = c.bg_highlight })
hi("ColorColumn", { bg = c.bg_highlight })
hi("LineNr", { fg = c.fg_gutter })
hi("LineNrAbove", { fg = c.fg_gutter })
hi("LineNrBelow", { fg = c.fg_gutter })
hi("SignColumn", { fg = c.fg_gutter, bg = c.none })
hi("FoldColumn", { fg = c.fg_gutter, bg = c.none })
hi("Folded", { fg = c.blue, bg = c.bg_highlight })
hi("Visual", { bg = c.bg_visual })
hi("VisualNOS", { bg = c.bg_visual })
hi("Search", { fg = c.bg, bg = c.blue2 })
hi("IncSearch", { fg = c.bg, bg = c.orange })
hi("CurSearch", { fg = c.bg, bg = c.orange })
hi("MatchParen", { fg = c.blue1, bold = true })
hi("Pmenu", { fg = c.fg, bg = c.bg_popup })
hi("PmenuSel", { fg = c.bg, bg = c.blue1, bold = true })
hi("PmenuSbar", { bg = c.bg_highlight })
hi("PmenuThumb", { bg = c.fg_gutter })
hi("WildMenu", { fg = c.bg, bg = c.blue1 })
hi("StatusLine", { fg = c.fg_dark, bg = c.none })
hi("StatusLineNC", { fg = c.fg_gutter, bg = c.none })
hi("WinBar", { fg = c.fg_dark, bg = c.none })
hi("WinBarNC", { fg = c.fg_gutter, bg = c.none })
hi("WinSeparator", { fg = c.bg_highlight })
hi("TabLine", { fg = c.fg_gutter, bg = c.none })
hi("TabLineFill", { bg = c.none })
hi("TabLineSel", { fg = c.blue1, bg = c.none, bold = true })
hi("NonText", { fg = c.fg_gutter })
hi("Whitespace", { fg = c.fg_gutter })
hi("SpecialKey", { fg = c.fg_gutter })
hi("EndOfBuffer", { fg = c.bg })
hi("Conceal", { fg = c.dark3 })
hi("Directory", { fg = c.blue1 })
hi("Title", { fg = c.blue1, bold = true })
hi("ModeMsg", { fg = c.fg_dark, bold = true })
hi("MsgArea", { fg = c.fg_dark })
hi("MoreMsg", { fg = c.blue1 })
hi("Question", { fg = c.blue1 })
hi("ErrorMsg", { fg = c.error })
hi("WarningMsg", { fg = c.warning })
hi("QuickFixLine", { bg = c.bg_highlight, bold = true })
hi("SpellBad", { sp = c.error, undercurl = true })
hi("SpellCap", { sp = c.warning, undercurl = true })
hi("SpellLocal", { sp = c.info, undercurl = true })
hi("SpellRare", { sp = c.hint, undercurl = true })

-- ── Legacy syntax groups ─────────────────────────────────────────────────────

hi("Comment", { fg = c.comment, italic = true })
hi("Constant", { fg = c.orange })
hi("String", { fg = c.green })
hi("Character", { fg = c.green })
hi("Number", { fg = c.orange })
hi("Boolean", { fg = c.orange })
hi("Float", { fg = c.orange })
hi("Identifier", { fg = c.fg })
hi("Function", { fg = c.blue })
hi("Statement", { fg = c.magenta, italic = true })
hi("Conditional", { fg = c.magenta, italic = true })
hi("Repeat", { fg = c.magenta, italic = true })
hi("Label", { fg = c.blue1 })
hi("Operator", { fg = c.blue5 })
hi("Keyword", { fg = c.magenta, italic = true })
hi("Exception", { fg = c.magenta, italic = true })
hi("PreProc", { fg = c.blue1 })
hi("Include", { fg = c.blue1 })
hi("Define", { fg = c.blue1 })
hi("Macro", { fg = c.blue1 })
hi("Type", { fg = c.blue5 })
hi("StorageClass", { fg = c.blue5 })
hi("Structure", { fg = c.blue5 })
hi("Typedef", { fg = c.blue5 })
hi("Special", { fg = c.blue1 })
hi("SpecialChar", { fg = c.blue1 })
hi("Tag", { fg = c.blue1 })
hi("Delimiter", { fg = c.blue5 })
hi("SpecialComment", { fg = c.comment, bold = true })
hi("Underlined", { fg = c.blue, underline = true })
hi("Ignore", { fg = c.comment })
hi("Todo", { fg = c.bg, bg = c.blue1, bold = true })
hi("Error", { fg = c.error, bold = true })

-- ── Treesitter (@-captures) ──────────────────────────────────────────────────

hi("@variable", { fg = c.fg })
hi("@variable.builtin", { fg = c.blue1, italic = true })
hi("@variable.parameter", { fg = c.fg_dark })
hi("@variable.member", { fg = c.fg_dark })
hi("@constant", { fg = c.orange })
hi("@constant.builtin", { fg = c.orange, italic = true })
hi("@constant.macro", { fg = c.blue1 })
hi("@module", { fg = c.blue5 })
hi("@label", { fg = c.blue1 })
hi("@string", { fg = c.green })
hi("@string.escape", { fg = c.magenta })
hi("@string.special", { fg = c.blue1 })
hi("@string.regexp", { fg = c.blue2 })
hi("@character", { fg = c.green })
hi("@character.special", { fg = c.blue1 })
hi("@number", { fg = c.orange })
hi("@boolean", { fg = c.orange })
hi("@float", { fg = c.orange })
hi("@function", { fg = c.blue })
hi("@function.builtin", { fg = c.blue1, italic = true })
hi("@function.macro", { fg = c.blue })
hi("@function.method", { fg = c.blue })
hi("@constructor", { fg = c.blue5 })
hi("@operator", { fg = c.blue5 })
hi("@keyword", { fg = c.magenta, italic = true })
hi("@keyword.function", { fg = c.magenta, italic = true })
hi("@keyword.return", { fg = c.magenta, italic = true })
hi("@keyword.operator", { fg = c.magenta, italic = true })
hi("@keyword.import", { fg = c.blue1 })
hi("@conditional", { fg = c.magenta, italic = true })
hi("@repeat", { fg = c.magenta, italic = true })
hi("@exception", { fg = c.magenta, italic = true })
hi("@punctuation.delimiter", { fg = c.blue5 })
hi("@punctuation.bracket", { fg = c.fg_dark })
hi("@punctuation.special", { fg = c.blue1 })
hi("@comment", { fg = c.comment, italic = true })
hi("@comment.documentation", { fg = c.comment, italic = true })
hi("@tag", { fg = c.blue1 })
hi("@tag.attribute", { fg = c.blue5 })
hi("@tag.delimiter", { fg = c.blue5 })
hi("@type", { fg = c.blue5 })
hi("@type.builtin", { fg = c.blue5, italic = true })
hi("@attribute", { fg = c.blue1 })
hi("@property", { fg = c.fg_dark })
hi("@markup.strong", { bold = true })
hi("@markup.italic", { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.underline", { underline = true })
hi("@markup.heading", { fg = c.blue1, bold = true })
hi("@markup.link", { fg = c.blue })
hi("@markup.link.url", { fg = c.green, underline = true })
hi("@markup.raw", { fg = c.green })
hi("@markup.list", { fg = c.blue5 })
hi("@diff.plus", { fg = c.git.add })
hi("@diff.minus", { fg = c.git.delete })
hi("@diff.delta", { fg = c.git.change })

-- ── LSP semantic tokens (fall back to @-captures above when unset) ──────────

-- Left empty/linked to their treesitter equivalents on purpose: semantic
-- tokens render above regular treesitter captures, so a real color here
-- would paint over (and hide) core.rainbow_var's per-identifier extmarks.
hi("@lsp.type.parameter", { link = "@variable.parameter" })
hi("@lsp.type.property", { link = "@property" })
hi("@lsp.type.variable", {})
hi("@lsp.mod.readonly", { italic = true })
hi("@lsp.typemod.variable.defaultLibrary", { fg = c.blue1, italic = true })

-- ── Diagnostics ──────────────────────────────────────────────────────────────

hi("DiagnosticError", { fg = c.error })
hi("DiagnosticWarn", { fg = c.warning })
hi("DiagnosticInfo", { fg = c.info })
hi("DiagnosticHint", { fg = c.hint })
hi("DiagnosticOk", { fg = c.green })
hi("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
hi("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
hi("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
hi("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
hi("DiagnosticVirtualTextError", { fg = c.error, bg = c.none })
hi("DiagnosticVirtualTextWarn", { fg = c.warning, bg = c.none })
hi("DiagnosticVirtualTextInfo", { fg = c.info, bg = c.none })
hi("DiagnosticVirtualTextHint", { fg = c.hint, bg = c.none })
hi("DiagnosticFloatingError", { fg = c.error })
hi("DiagnosticFloatingWarn", { fg = c.warning })
hi("DiagnosticFloatingInfo", { fg = c.info })
hi("DiagnosticFloatingHint", { fg = c.hint })
hi("DiagnosticSignError", { fg = c.error })
hi("DiagnosticSignWarn", { fg = c.warning })
hi("DiagnosticSignInfo", { fg = c.info })
hi("DiagnosticSignHint", { fg = c.hint })
hi("LspInlayHint", { fg = c.comment, bg = c.none, italic = true })
hi("LspReferenceText", { bg = c.bg_highlight })
hi("LspReferenceRead", { bg = c.bg_highlight })
hi("LspReferenceWrite", { bg = c.bg_highlight })
hi("LspCodeLens", { fg = c.comment })
hi("LspSignatureActiveParameter", { fg = c.orange, bold = true })

-- ── Diffs / GitSigns ─────────────────────────────────────────────────────────

hi("DiffAdd", { bg = c.diff.add })
hi("DiffChange", { bg = c.diff.change })
hi("DiffDelete", { bg = c.diff.delete })
hi("DiffText", { bg = c.diff.text })
hi("diffAdded", { fg = c.git.add })
hi("diffRemoved", { fg = c.git.delete })
hi("diffChanged", { fg = c.git.change })

hi("GitSignsAdd", { fg = c.git.add })
hi("GitSignsChange", { fg = c.git.change })
hi("GitSignsDelete", { fg = c.git.delete })
hi("GitSignsAddNr", { fg = c.git.add })
hi("GitSignsChangeNr", { fg = c.git.change })
hi("GitSignsDeleteNr", { fg = c.git.delete })
hi("GitSignsAddLn", { bg = c.diff.add })
hi("GitSignsChangeLn", { bg = c.diff.change })
hi("GitSignsDeleteLn", { bg = c.diff.delete })
hi("GitSignsCurrentLineBlame", { fg = c.comment, italic = true })

-- ── Telescope ────────────────────────────────────────────────────────────────

hi("TelescopeNormal", { fg = c.fg, bg = c.bg_float })
hi("TelescopeBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("TelescopePromptNormal", { fg = c.fg, bg = c.bg_float })
hi("TelescopePromptBorder", { fg = c.orange, bg = c.bg_float })
hi("TelescopePromptTitle", { fg = c.orange, bg = c.bg_float })
hi("TelescopeResultsComment", { fg = c.dark3 })
hi("TelescopeSelection", { fg = c.fg, bg = c.bg_highlight, bold = true })
hi("TelescopeMatching", { fg = c.orange, bold = true })
hi("TelescopeMultiSelection", { fg = c.magenta })

-- ── which-key ────────────────────────────────────────────────────────────────

hi("WhichKey", { fg = c.blue1, bold = true })
hi("WhichKeyGroup", { fg = c.blue })
hi("WhichKeyDesc", { fg = c.magenta })
hi("WhichKeySeparator", { fg = c.comment })
hi("WhichKeyNormal", { bg = c.bg_sidebar })
hi("WhichKeyBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("WhichKeyTitle", { fg = c.blue1, bg = c.bg_float, bold = true })
hi("WhichKeyValue", { fg = c.dark5 })

-- ── Trouble ──────────────────────────────────────────────────────────────────

hi("TroubleNormal", { fg = c.fg, bg = c.none })
hi("TroubleNormalNC", { fg = c.fg_dark, bg = c.none })
hi("TroubleText", { fg = c.fg_dark })
hi("TroubleCount", { fg = c.blue1, bold = true })
hi("TroubleIndent", { fg = c.fg_gutter })
hi("TroubleSource", { fg = c.comment })
hi("TroubleCode", { fg = c.comment })
hi("TroubleFilename", { fg = c.blue })
hi("TroubleDirectory", { fg = c.fg_dark })
hi("TroublePos", { fg = c.comment })

-- ── blink.cmp ────────────────────────────────────────────────────────────────

hi("BlinkCmpMenu", { fg = c.fg, bg = c.bg_float })
hi("BlinkCmpMenuBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("BlinkCmpMenuSelection", { fg = c.fg, bg = c.bg_highlight, bold = true })
hi("BlinkCmpLabel", { fg = c.fg, bg = c.none })
hi("BlinkCmpLabelDeprecated", { fg = c.fg_gutter, bg = c.none, strikethrough = true })
hi("BlinkCmpLabelMatch", { fg = c.blue1, bg = c.none })
hi("BlinkCmpLabelDetail", { fg = c.comment })
hi("BlinkCmpLabelDescription", { fg = c.comment })
hi("BlinkCmpKind", { fg = c.fg_dark, bg = c.none })
hi("BlinkCmpDoc", { fg = c.fg, bg = c.bg_float })
hi("BlinkCmpDocBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("BlinkCmpDocSeparator", { fg = c.comment })
hi("BlinkCmpSignatureHelp", { fg = c.fg, bg = c.bg_float })
hi("BlinkCmpSignatureHelpBorder", { fg = c.border_highlight, bg = c.bg_float })
hi("BlinkCmpSignatureHelpActiveParameter", { fg = c.orange, bold = true })
hi("BlinkCmpSource", { fg = c.comment })
hi("BlinkCmpGhostText", { fg = c.terminal_black })

-- ── snacks.nvim (dashboard/notifier/indent) ──────────────────────────────────

hi("SnacksDashboardHeader", { fg = c.blue1 })
hi("SnacksDashboardFooter", { fg = c.comment })
hi("SnacksDashboardSpecial", { fg = c.orange, bold = true })
hi("SnacksDashboardIcon", { fg = c.blue })
hi("SnacksDashboardDesc", { fg = c.fg })
hi("SnacksDashboardKey", { fg = c.orange })
hi("SnacksNotifierInfo", { fg = c.info })
hi("SnacksNotifierWarn", { fg = c.warning })
hi("SnacksNotifierError", { fg = c.error })
hi("SnacksIndent", { fg = c.fg_gutter })
hi("SnacksIndentScope", { fg = c.blue1 })
hi("SnacksPickerInputBorder", { fg = c.orange, bg = c.bg_float })
hi("SnacksPickerInputTitle", { fg = c.orange, bg = c.bg_float })
hi("SnacksPickerBoxTitle", { fg = c.orange, bg = c.bg_float })
hi("SnacksPickerMatch", { fg = c.orange, bold = true })
hi("SnacksPickerSelected", { fg = c.magenta2 })

-- ── fidget.nvim (LSP progress) ───────────────────────────────────────────────

-- fidget.nvim's LSP progress display links to the standard Title group
-- (group_style = "Title" by default), no fidget-specific groups needed.

-- ── todo-comments ────────────────────────────────────────────────────────────

hi("TodoBgTODO", { fg = c.bg, bg = c.blue1, bold = true })
hi("TodoBgFIX", { fg = c.bg, bg = c.error, bold = true })
hi("TodoBgWARN", { fg = c.bg, bg = c.warning, bold = true })
hi("TodoBgNOTE", { fg = c.bg, bg = c.hint, bold = true })
hi("TodoFgTODO", { fg = c.blue1 })
hi("TodoFgFIX", { fg = c.error })
hi("TodoFgWARN", { fg = c.warning })
hi("TodoFgNOTE", { fg = c.hint })

-- ── rainbow-delimiters ───────────────────────────────────────────────────────

for i, color in ipairs(c.rainbow) do
  hi("RainbowDelimiter" .. i, { fg = color })
end

-- ── terminal colors (:terminal buffers) ──────────────────────────────────────

vim.g.terminal_color_0 = c.terminal.black
vim.g.terminal_color_1 = c.terminal.red
vim.g.terminal_color_2 = c.terminal.green
vim.g.terminal_color_3 = c.terminal.yellow
vim.g.terminal_color_4 = c.terminal.blue
vim.g.terminal_color_5 = c.terminal.magenta
vim.g.terminal_color_6 = c.terminal.cyan
vim.g.terminal_color_7 = c.terminal.white
vim.g.terminal_color_8 = c.terminal.black_bright
vim.g.terminal_color_9 = c.terminal.red_bright
vim.g.terminal_color_10 = c.terminal.green_bright
vim.g.terminal_color_11 = c.terminal.yellow_bright
vim.g.terminal_color_12 = c.terminal.blue_bright
vim.g.terminal_color_13 = c.terminal.magenta_bright
vim.g.terminal_color_14 = c.terminal.cyan_bright
vim.g.terminal_color_15 = c.terminal.white_bright
